const SCHEMA = "radprompt.v1";
const STATE_KEY = "radprompt:state:v1";
const BACKUP_KEY_PREFIX = "radprompt:backup:";
const MAX_JSON_BYTES = 24 * 1024 * 1024;
const MAX_TEXT_BYTES = 24 * 1024 * 1024;
const MAX_BODY_CHARS = 5_000_000;
const DEFAULT_FOLDERS = [{ id: "befundung", name: "Befundung", icon: "scan-search", order: 0 }, { id: "prof-schaefer", name: "Prof. Schäfer", icon: "stethoscope", order: 1 }, { id: "wissen", name: "Wissen", icon: "book-open", order: 2 }, { id: "allgemein", name: "Allgemein", icon: "sparkles", order: 3 }];
const DOCUMENT_TITLES = { schaeferCt: "# Befundbeispiele Prof. Schäfer CT.txt", schaeferMrt: "# Befundbeispiele Prof. Schäfer MRT.txt" };
const DATA_ASSETS = { prompts: "/data/Beispielprompts.txt", schaeferCt: "/data/Befundbeispiele Prof. Schäfer CT.txt", schaeferMrt: "/data/Befundbeispiele Prof. Schäfer MRT.txt" };
const DEFAULT_SETTINGS = { compactMode: false, effects: true, autosave: true, viewMode: "grid", sortMode: "manual", activeView: "all", selectedFolder: "all", denseCards: false };
const JSON_HEADERS = { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0", "Pragma": "no-cache", "Expires": "0", "X-Content-Type-Options": "nosniff" };
const TEXT_HEADERS = { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0", "Pragma": "no-cache", "Expires": "0", "X-Content-Type-Options": "nosniff" };
export async function onRequest(context) { const h = createHelpers(context); context.data.radprompt = h; if (h.isApiRequest && context.request.method === "OPTIONS") return new Response(null, { status: 204, headers: h.apiHeaders() }); try { const response = await context.next(); return h.finalizeResponse(response); } catch (error) { return h.error(error, { status: error.status || error.statusCode || 500 }); } }
function createHelpers(context) { const request = context.request; const url = new URL(request.url); const isApiRequest = url.pathname === "/api" || url.pathname.startsWith("/api/"); const startedAt = Date.now(); const h = { schema: SCHEMA, stateKey: STATE_KEY, backupKeyPrefix: BACKUP_KEY_PREFIX, maxJsonBytes: MAX_JSON_BYTES, maxTextBytes: MAX_TEXT_BYTES, documentTitles: DOCUMENT_TITLES, dataAssets: DATA_ASSETS, isApiRequest, startedAt, context, request, url, env: context.env || {}, apiHeaders, json, text, error, finalizeResponse, requireMethod, requireKv, kv, getKv, putKv, deleteKv, listKv, readJson, readText, safeJsonParse, emptyState, normalizeState, normalizePrompt, normalizeFolder, normalizeDocument, normalizeSettings, summarizeState, parsePromptFile, parseBoolean, extractPlaceholders, classifyPrompt, classifyFolder, accentForPrompt, describePrompt, getAssetText, getAssetMeta, assetCandidates, hashText, hashJson, stableStringify, jsonReplacer, byteLength, runtimeInfo, cleanText, cleanId, slugify, unique, now, validDate, uid, backupKey, backupState, compactStateForStorage, ensureWithinKvLimit }; return h;
  function apiHeaders(extra = {}) { const headers = new Headers(JSON_HEADERS); headers.set("Access-Control-Allow-Origin", sameOriginAllowed() ? url.origin : "null"); headers.set("Access-Control-Allow-Methods", "GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS"); headers.set("Access-Control-Allow-Headers", "Content-Type,Accept,If-Match,If-None-Match,X-RadPrompt-Hash"); headers.set("Access-Control-Expose-Headers", "ETag,X-RadPrompt-Hash,X-RadPrompt-Version,X-RadPrompt-Bytes"); headers.set("Vary", "Origin"); headers.set("Referrer-Policy", "strict-origin-when-cross-origin"); headers.set("X-Frame-Options", "DENY"); headers.set("Cross-Origin-Opener-Policy", "same-origin"); headers.set("Cross-Origin-Resource-Policy", "same-origin"); for (const [key, value] of Object.entries(extra || {})) headers.set(key, String(value)); return headers; }
  function sameOriginAllowed() { const origin = request.headers.get("Origin"); if (!origin) return true; try { return new URL(origin).origin === url.origin; } catch { return false; } }
  function json(payload, init = {}) { const status = init.status || 200; const headers = apiHeaders(init.headers || {}); const body = JSON.stringify(payload, jsonReplacer, init.pretty === false ? 0 : 2); headers.set("X-RadPrompt-Bytes", String(byteLength(body))); return new Response(body, { status, headers }); }
  function text(body = "", init = {}) { const status = init.status || 200; const headers = new Headers(TEXT_HEADERS); for (const [key, value] of Object.entries(init.headers || {})) headers.set(key, String(value)); if (isApiRequest) return new Response(String(body), { status, headers: apiHeaders(Object.fromEntries(headers.entries())) }); return new Response(String(body), { status, headers }); }
  function error(err, init = {}) { const status = normalizeStatus(init.status || err?.status || err?.statusCode || 500); const message = status >= 500 ? "Interner RadPrompt-Fehler." : cleanText(err?.message || "RadPrompt-Fehler.", 600); const payload = { ok: false, error: status >= 500 ? "internal_error" : "request_error", message, status, runtime: runtimeInfo() }; if (shouldExposeDebug()) payload.detail = String(err?.stack || err?.message || err || ""); return json(payload, { status }); }
  function finalizeResponse(response) { if (!isApiRequest) return response; const headers = apiHeaders(Object.fromEntries(response.headers.entries())); if (!headers.has("Content-Type")) headers.set("Content-Type", "application/json; charset=utf-8"); headers.set("X-RadPrompt-Runtime", String(Date.now() - startedAt)); return new Response(response.body, { status: response.status, statusText: response.statusText, headers }); }
  function requireMethod(methods) { const allowed = (Array.isArray(methods) ? methods : [methods]).map(item => String(item).toUpperCase()); if (!allowed.includes(request.method.toUpperCase())) { const err = new Error(`Methode ${request.method} nicht erlaubt. Erlaubt: ${allowed.join(", ")}.`); err.status = 405; throw err; } }
  function requireKv() { if (!kv()) { const err = new Error("RADPROMPT_KV ist nicht gebunden. Im Cloudflare Pages Dashboard muss ein KV namespace binding mit dem Namen RADPROMPT_KV gesetzt werden."); err.status = 503; throw err; } }
  function kv() { return context.env?.RADPROMPT_KV || null; }
  async function getKv(key, options = {}) { requireKv(); return kv().get(String(key), options.type || options.cacheTtl ? options : undefined); }
  async function putKv(key, value, options = {}) { requireKv(); const body = typeof value === "string" ? value : JSON.stringify(value, jsonReplacer); ensureWithinKvLimit(body); const putOptions = {}; if (options.metadata) putOptions.metadata = options.metadata; if (Number.isFinite(Number(options.expiration))) putOptions.expiration = Number(options.expiration); if (Number.isFinite(Number(options.expirationTtl))) putOptions.expirationTtl = Number(options.expirationTtl); return kv().put(String(key), body, Object.keys(putOptions).length ? putOptions : undefined); }
  async function deleteKv(key) { requireKv(); return kv().delete(String(key)); }
  async function listKv(options = {}) { requireKv(); const args = {}; if (options.prefix) args.prefix = String(options.prefix); if (options.limit) args.limit = Math.max(1, Math.min(1000, Number(options.limit) || 100)); if (options.cursor) args.cursor = String(options.cursor); return kv().list(args); }
  async function readJson(options = {}) { if (request.method === "GET" || request.method === "HEAD") return {}; const raw = await request.clone().text(); if (byteLength(raw) > (options.maxBytes || MAX_JSON_BYTES)) { const err = new Error(`JSON-Body zu groß. Maximum: ${options.maxBytes || MAX_JSON_BYTES} Bytes.`); err.status = 413; throw err; } if (!raw.trim()) return {}; const type = request.headers.get("Content-Type") || ""; if (type && !type.includes("application/json") && !type.includes("+json")) { const err = new Error("Content-Type muss application/json sein."); err.status = 415; throw err; } try { return JSON.parse(raw); } catch { const err = new Error("Ungültiges JSON."); err.status = 400; throw err; } }
  async function readText(options = {}) { const raw = await request.clone().text(); if (byteLength(raw) > (options.maxBytes || MAX_TEXT_BYTES)) { const err = new Error(`Text-Body zu groß. Maximum: ${options.maxBytes || MAX_TEXT_BYTES} Bytes.`); err.status = 413; throw err; } return raw; }
  function safeJsonParse(raw, fallback = null) { try { return JSON.parse(String(raw || "")); } catch { return fallback; } }
  function emptyState() { const t = now(); return { schema: SCHEMA, version: 0, updatedAt: t, folders: DEFAULT_FOLDERS.map(folder => ({ ...folder, createdAt: t, updatedAt: t })), prompts: [], favorites: [], documents: { schaeferCt: { title: DOCUMENT_TITLES.schaeferCt, text: "", updatedAt: "" }, schaeferMrt: { title: DOCUMENT_TITLES.schaeferMrt, text: "", updatedAt: "" } }, settings: { ...DEFAULT_SETTINGS }, meta: { seededAt: "", source: "", hash: "" } }; }
  function normalizeState(input = {}) { const base = emptyState(); const raw = input && typeof input === "object" ? input : {}; const folders = dedupeById((Array.isArray(raw.folders) && raw.folders.length ? raw.folders : base.folders).map(normalizeFolder).filter(item => item.id && item.name)); const fallbackFolder = folders[0]?.id || "allgemein"; const folderIds = new Set(folders.map(item => item.id)); const prompts = dedupeById((Array.isArray(raw.prompts) ? raw.prompts : []).map((item, index) => { const prompt = normalizePrompt(item, fallbackFolder); if (!folderIds.has(prompt.folderId)) prompt.folderId = fallbackFolder; if (!Number.isFinite(Number(prompt.order))) prompt.order = index; return prompt; }).filter(item => item.id && item.title)); const promptIds = new Set(prompts.map(item => item.id)); const favorites = unique([...(Array.isArray(raw.favorites) ? raw.favorites : []), ...prompts.filter(item => item.favorite).map(item => item.id)]).map(cleanId).filter(id => promptIds.has(id)); return { schema: SCHEMA, version: Math.max(0, Number(raw.version || 0)), updatedAt: validDate(raw.updatedAt) || base.updatedAt, folders: folders.sort((a, b) => Number(a.order || 0) - Number(b.order || 0) || a.name.localeCompare(b.name, "de", { sensitivity: "base" })).map((folder, index) => ({ ...folder, order: index })), prompts, favorites, documents: { schaeferCt: normalizeDocument(raw.documents?.schaeferCt, { title: DOCUMENT_TITLES.schaeferCt, text: "", updatedAt: "" }), schaeferMrt: normalizeDocument(raw.documents?.schaeferMrt, { title: DOCUMENT_TITLES.schaeferMrt, text: "", updatedAt: "" }) }, settings: normalizeSettings(raw.settings), meta: normalizeMeta(raw.meta) }; }
  function normalizePrompt(input = {}, fallbackFolder = "allgemein") { const t = now(); const title = cleanText(input.title || "Unbenannter Prompt", 180); const body = cleanText(input.body || "", MAX_BODY_CHARS); const kind = cleanText(input.kind || classifyPrompt(title, body), 64); return { id: cleanId(input.id || slugify(title) || uid("prompt")), title, description: cleanText(input.description || "", 500), folderId: cleanId(input.folderId || fallbackFolder || "allgemein"), body, kind, accent: cleanText(input.accent || accentForPrompt(title, kind), 48), favorite: Boolean(input.favorite), appendSchaeferCt: Boolean(input.appendSchaeferCt), appendSchaeferMrt: Boolean(input.appendSchaeferMrt), order: Number.isFinite(Number(input.order)) ? Number(input.order) : 0, createdAt: validDate(input.createdAt) || t, updatedAt: validDate(input.updatedAt) || t, lastUsedAt: validDate(input.lastUsedAt) || "" }; }
  function normalizeFolder(input = {}) { const t = now(); return { id: cleanId(input.id || slugify(input.name || "ordner") || uid("folder")), name: cleanText(input.name || "Ordner", 180), icon: cleanText(input.icon || "folder", 80), order: Number.isFinite(Number(input.order)) ? Number(input.order) : 0, createdAt: validDate(input.createdAt) || t, updatedAt: validDate(input.updatedAt) || t }; }
  function normalizeDocument(input = {}, fallback = {}) { return { title: cleanText(input?.title || fallback.title || "", 240), text: cleanText(input?.text || fallback.text || "", MAX_BODY_CHARS * 2), updatedAt: validDate(input?.updatedAt) || fallback.updatedAt || "" }; }
  function normalizeSettings(input = {}) { const raw = input && typeof input === "object" ? input : {}; return { compactMode: Boolean(raw.compactMode), effects: raw.effects === undefined ? true : Boolean(raw.effects), autosave: raw.autosave === undefined ? true : Boolean(raw.autosave), viewMode: ["grid", "list"].includes(raw.viewMode) ? raw.viewMode : "grid", sortMode: ["manual", "alpha", "recent", "used"].includes(raw.sortMode) ? raw.sortMode : "manual", activeView: cleanText(raw.activeView || "all", 60), selectedFolder: cleanText(raw.selectedFolder || "all", 120), denseCards: Boolean(raw.denseCards) }; }
  function normalizeMeta(input = {}) { const raw = input && typeof input === "object" ? input : {}; return { seededAt: validDate(raw.seededAt) || "", source: cleanText(raw.source || "", 120), hash: cleanText(raw.hash || "", 128) }; }
  function summarizeState(state) { const normalized = normalizeState(state); return { schema: normalized.schema, version: normalized.version, folders: normalized.folders.length, prompts: normalized.prompts.length, favorites: normalized.favorites.length, documents: { schaeferCt: { title: normalized.documents.schaeferCt.title, bytes: byteLength(normalized.documents.schaeferCt.text), updatedAt: normalized.documents.schaeferCt.updatedAt }, schaeferMrt: { title: normalized.documents.schaeferMrt.title, bytes: byteLength(normalized.documents.schaeferMrt.text), updatedAt: normalized.documents.schaeferMrt.updatedAt } }, bytes: byteLength(JSON.stringify(normalized, jsonReplacer)), updatedAt: normalized.updatedAt, seededAt: normalized.meta.seededAt || "", hash: normalized.meta.hash || "" }; }
  function parsePromptFile(text) { const source = cleanText(text || "", MAX_BODY_CHARS).replace(/\r\n?/g, "\n"); const matches = [...source.matchAll(/^\/\/\s*(.+?):\s*$/gm)]; const prompts = []; for (let index = 0; index < matches.length; index++) { const title = cleanText(matches[index][1], 180); const start = matches[index].index + matches[index][0].length; const end = index + 1 < matches.length ? matches[index + 1].index : source.length; const body = cleanText(source.slice(start, end), MAX_BODY_CHARS); if (!title || !body) continue; const kind = classifyPrompt(title, body); prompts.push(normalizePrompt({ id: uniquePromptId(prompts, slugify(title) || uid("prompt")), title, description: describePrompt(title, body, kind), folderId: classifyFolder(title, body, kind), body, kind, accent: accentForPrompt(title, kind), favorite: index < 4, appendSchaeferCt: kind === "schaefer", appendSchaeferMrt: kind === "schaefer", order: prompts.length, createdAt: now(), updatedAt: now() })); } return { ok: true, prompts, count: prompts.length, bytes: byteLength(source), placeholders: unique(prompts.flatMap(prompt => extractPlaceholders(prompt.body))) }; }
  function uniquePromptId(prompts, root) { const ids = new Set(prompts.map(item => item.id)); let id = cleanId(root) || uid("prompt"); let i = 2; while (ids.has(id)) id = `${cleanId(root)}-${i++}`; return id; }
  function extractPlaceholders(text) { const found = []; String(text || "").replace(/\*\*\*([^*]+?)\*\*\*/g, (_, name) => { const cleaned = cleanText(name, 140).replace(/\s+/g, " "); if (cleaned) found.push(cleaned); return ""; }); return unique(found); }
  function classifyPrompt(title, body) { const haystack = normalizeSearch(`${title} ${body}`); if (haystack.includes("prof schafer") || haystack.includes("prof schaefer") || haystack.includes("befundstil")) return "schaefer"; if (extractPlaceholders(body).length) return "special"; return "standard"; }
  function classifyFolder(title, body, kind) { const haystack = normalizeSearch(`${title} ${body}`); if (kind === "schaefer") return "prof-schaefer"; if (haystack.includes("protokoll") || haystack.includes("staging") || haystack.includes("ubersicht") || haystack.includes("übersicht") || haystack.includes("klassifikation")) return "wissen"; if (haystack.includes("befund") || haystack.includes("bildinterpretation") || haystack.includes("radiologisch")) return "befundung"; return "allgemein"; }
  function accentForPrompt(title, kind) { const haystack = normalizeSearch(`${title} ${kind}`); if (kind === "schaefer") return "violet"; if (haystack.includes("revision")) return "amber"; if (haystack.includes("staging")) return "red"; if (haystack.includes("protokoll")) return "cyan"; if (haystack.includes("ubersicht") || haystack.includes("übersicht")) return "emerald"; return "blue"; }
  function describePrompt(title, body, kind) { if (kind === "schaefer") return "Prompt zur kompakten Prof.-Schäfer-Stiloptimierung mit optionalem CT-/MRT-Beispielanhang."; const placeholders = extractPlaceholders(body); return placeholders.length ? `Prompt mit ${placeholders.length} Platzhalter${placeholders.length === 1 ? "" : "n"}.` : cleanText(title, 220); }
  async function getAssetText(path, options = {}) { const errors = []; for (const candidate of assetCandidates(path)) { try { const response = await fetchAssetCandidate(candidate); if (response.ok) { const text = await response.text(); if (byteLength(text) > (options.maxBytes || MAX_TEXT_BYTES)) { const err = new Error(`Asset ${candidate} ist zu groß.`); err.status = 413; throw err; } return text; } errors.push(`${candidate}: ${response.status}`); } catch (error) { errors.push(`${candidate}: ${error.message || error}`); } } const err = new Error(`Asset nicht lesbar: ${path}. Versuche: ${errors.join("; ")}`); err.status = 404; throw err; }
  async function getAssetMeta(path) { const result = { path, exists: false, readable: false, bytes: 0, contentType: "", status: 0, usedPath: "", error: "" }; for (const candidate of assetCandidates(path)) { try { const response = await fetchAssetCandidate(candidate, "GET"); result.status = response.status; result.usedPath = candidate; result.contentType = response.headers.get("Content-Type") || ""; if (response.ok) { const text = await response.text(); result.exists = true; result.readable = true; result.bytes = byteLength(text); return result; } } catch (error) { result.error = error.message || String(error); } } return result; }
  async function fetchAssetCandidate(candidate, method = "GET") { if (context.env?.ASSETS?.fetch) return context.env.ASSETS.fetch(new Request(new URL(candidate, url.origin).toString(), { method })); return fetch(new URL(candidate, url.origin).toString(), { method }); }
  function assetCandidates(path) { const raw = String(path || "").trim(); const leading = raw.startsWith("/") ? raw : `/${raw}`; const decoded = safeDecodePath(leading); const encodedSegments = decoded.split("/").map((segment, index) => index === 0 ? "" : encodeURIComponent(segment)).join("/"); return unique([leading, decoded, encodedSegments, leading.replace(/\s/g, "%20"), decoded.replace(/\s/g, "%20")]); }
  function safeDecodePath(path) { try { return decodeURI(path); } catch { return path; } }
  async function hashText(text) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(String(text || ""))); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join(""); }
  async function hashJson(value) { return hashText(stableStringify(value)); }
  function stableStringify(value) { return JSON.stringify(sortDeep(value), jsonReplacer); }
  function sortDeep(value) { if (Array.isArray(value)) return value.map(sortDeep); if (value && typeof value === "object" && value.constructor === Object) { const out = {}; for (const key of Object.keys(value).sort()) out[key] = sortDeep(value[key]); return out; } return value; }
  function jsonReplacer(key, value) { if (typeof value === "bigint") return value.toString(); if (value instanceof Date) return value.toISOString(); if (value === undefined) return null; return value; }
  function byteLength(value) { return new TextEncoder().encode(String(value || "")).length; }
  function runtimeInfo() { return { endpoint: url.pathname, hostname: url.hostname, protocol: url.protocol, method: request.method, colo: request.cf?.colo || "", country: request.cf?.country || "", timezone: request.cf?.timezone || "", userAgent: request.headers.get("User-Agent") || "", ray: request.headers.get("CF-Ray") || "", kvBound: Boolean(kv()), assetsBound: Boolean(context.env?.ASSETS?.fetch), compatibility: context.env?.RADPROMPT_COMPATIBILITY || "", durationMs: Date.now() - startedAt }; }
  function parseBoolean(value, fallback = false) { if (typeof value === "boolean") return value; if (value === undefined || value === null || value === "") return fallback; const normalized = String(value).trim().toLowerCase(); if (["1", "true", "yes", "ja", "on"].includes(normalized)) return true; if (["0", "false", "no", "nein", "off"].includes(normalized)) return false; return fallback; }
  function cleanText(value, max = 1000000) { return String(value ?? "").normalize("NFKC").replace(/\r\n?/g, "\n").trim().slice(0, max); }
  function cleanId(value) { return slugify(value || "").slice(0, 140); }
  function slugify(value) { return String(value || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/Ä/g, "ae").replace(/Ö/g, "oe").replace(/Ü/g, "ue").replace(/ß/g, "ss").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100); }
  function normalizeSearch(value) { return String(value || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss").toLowerCase(); }
  function unique(list) { return [...new Set((Array.isArray(list) ? list : []).filter(item => item !== undefined && item !== null && String(item) !== ""))]; }
  function dedupeById(list) { const seen = new Set(); const out = []; for (const item of list) { if (!item?.id || seen.has(item.id)) continue; seen.add(item.id); out.push(item); } return out; }
  function now() { return new Date().toISOString(); }
  function validDate(value) { if (!value) return ""; const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toISOString() : ""; }
  function uid(prefix = "id") { const rand = crypto.getRandomValues(new Uint32Array(2)); return `${prefix}-${Date.now().toString(36)}-${rand[0].toString(36)}${rand[1].toString(36)}`; }
  function backupKey(label = "state") { return `${BACKUP_KEY_PREFIX}${new Date().toISOString().replace(/[:.]/g, "-")}:${cleanId(label) || "state"}`; }
  async function backupState(state, label = "state") { if (!kv()) return { ok: false, key: "", reason: "kv_missing" }; const normalized = normalizeState(state); const body = JSON.stringify(normalized, jsonReplacer); const key = backupKey(label); await putKv(key, body, { metadata: { schema: SCHEMA, version: normalized.version, updatedAt: normalized.updatedAt, label: cleanText(label, 80), bytes: byteLength(body) }, expirationTtl: 60 * 60 * 24 * 30 }); return { ok: true, key }; }
  function compactStateForStorage(state) { return normalizeState(state); }
  function ensureWithinKvLimit(value) { const bytes = byteLength(value); if (bytes > MAX_JSON_BYTES) { const err = new Error(`KV-Wert zu groß: ${bytes} Bytes. Maximum: ${MAX_JSON_BYTES} Bytes.`); err.status = 413; throw err; } }
  function shouldExposeDebug() { return ["localhost", "127.0.0.1"].includes(url.hostname) || url.searchParams.get("debug") === "1"; }
  function normalizeStatus(status) { const code = Number(status); return Number.isFinite(code) && code >= 100 && code <= 599 ? code : 500; }
}
