export async function onRequestGet(context){const h=context.data.radprompt;h.method(["GET","HEAD"]);const o=opts(h,{});const seed=await readSeed(h,o);const current=await currentLenient(h);const projected=await build(h,current.state,seed,{...o,dryRun:true});return h.json({ok:true,mode:"preview",dryRun:true,kvBound:Boolean(h.kv()),assets:seed.assets,parsed:seed.parsed,state:o.text?projected.state:mask(h,projected.state),summary:h.summarize(projected.state),import:projected.info,runtime:h.runtime()})}
export async function onRequestHead(context){const r=await onRequestGet(context);return new Response(null,{status:r.status,headers:r.headers})}
export async function onRequestPost(context){const h=context.data.radprompt;h.method(["POST"]);const body=await h.readJson();const o=opts(h,body);const seed=await readSeed(h,{...o,text:true});const current=o.dryRun?await currentLenient(h):await currentStrict(h);const projected=await build(h,current.state,seed,o);if(o.dryRun)return h.json({ok:true,mode:"dryRun",dryRun:true,written:false,assets:seed.assets,parsed:seed.parsed,state:o.text?projected.state:mask(h,projected.state),summary:h.summarize(projected.state),import:projected.info,runtime:h.runtime()});let backup={ok:false,key:"",reason:"missing"};if(current.exists&&current.readable)backup=await h.backupState(current.state,"before-seed");const payload=JSON.stringify(projected.state);await h.putKv(h.stateKey,payload,{metadata:{schema:h.schema,version:projected.state.version,updatedAt:projected.state.updatedAt,hash:projected.state.meta.hash,bytes:h.byteLength(payload),mode:"seed"}});return h.json({ok:true,written:true,backup,assets:seed.assets,parsed:seed.parsed,state:o.text?projected.state:mask(h,projected.state),summary:h.summarize(projected.state),import:projected.info,runtime:h.runtime()})}
function opts(h,b){const q=h.url.searchParams;const pick=(k,d)=>q.has(k)?h.parseBool(q.get(k),d):Object.prototype.hasOwnProperty.call(b,k)?h.parseBool(b[k],d):d;return{prompts:pick("prompts",true),schaeferCt:pick("schaeferCt",true),schaeferMrt:pick("schaeferMrt",true),replace:pick("replace",true),dryRun:pick("dryRun",false),favoriteFirst:pick("favoriteFirst",true),text:pick("text",false)||pick("includeText",false)}}
async function currentLenient(h){if(!h.kv())return{exists:false,readable:true,state:h.emptyState()};try{return await currentStrict(h)}catch{return{exists:false,readable:false,state:h.emptyState()}}}
async function currentStrict(h){h.requireKv();const raw=await h.getKv(h.stateKey);if(!raw)return{exists:false,readable:true,state:h.emptyState()};try{return{exists:true,readable:true,state:h.normalizeState(JSON.parse(raw))}}catch{const e=new Error("Vorhandener State ist ungültig.");e.status=409;throw e}}
async function readSeed(h,o){const assets={};const parsed={prompts:null,schaeferCt:null,schaeferMrt:null};const texts={prompts:"",schaeferCt:"",schaeferMrt:""};if(o.prompts){texts.prompts=await h.assetText(h.assets.prompts);assets.prompts=await h.assetMeta(h.assets.prompts);parsed.prompts=h.parsePrompts(texts.prompts)}if(o.schaeferCt){texts.schaeferCt=await h.assetText(h.assets.schaeferCt);assets.schaeferCt=await h.assetMeta(h.assets.schaeferCt);parsed.schaeferCt={ok:true,bytes:h.byteLength(texts.schaeferCt),hash:await h.hashText(texts.schaeferCt)}}if(o.schaeferMrt){texts.schaeferMrt=await h.assetText(h.assets.schaeferMrt);assets.schaeferMrt=await h.assetMeta(h.assets.schaeferMrt);parsed.schaeferMrt={ok:true,bytes:h.byteLength(texts.schaeferMrt),hash:await h.hashText(texts.schaeferMrt)}}return{assets,parsed,texts}}
async function build(h,current,seed,o){const state=o.replace?h.emptyState():h.normalizeState(current);const info={promptsAdded:0,promptsUpdated:0,documentsUpdated:[],favoritesAdded:0};if(seed.parsed.prompts?.prompts){const byTitle=new Map(state.prompts.map(p=>[norm(p.title),p]));for(const p of seed.parsed.prompts.prompts){const old=byTitle.get(norm(p.title));if(old){Object.assign(old,p,{id:old.id,updatedAt:h.now()});info.promptsUpdated++}else{state.prompts.push(p);info.promptsAdded++}}}if(o.schaeferCt&&seed.texts.schaeferCt){state.documents.schaeferCt={title:h.titles.schaeferCt,text:seed.texts.schaeferCt,updatedAt:h.now()};info.documentsUpdated.push("schaeferCt")}if(o.schaeferMrt&&seed.texts.schaeferMrt){state.documents.schaeferMrt={title:h.titles.schaeferMrt,text:seed.texts.schaeferMrt,updatedAt:h.now()};info.documentsUpdated.push("schaeferMrt")}for(const p of state.prompts){const s=norm(`${p.title} ${p.body}`);if(s.includes("prof schafer")||s.includes("prof schaefer")||s.includes("befundstil")){p.kind="schaefer";p.folderId="prof-schaefer";p.accent="violet";p.appendSchaeferCt=true;p.appendSchaeferMrt=true}}if(o.favoriteFirst&&!state.favorites.length){state.favorites=state.prompts.slice(0,4).map(p=>p.id);info.favoritesAdded=state.favorites.length}const normalized=h.normalizeState(state);normalized.version=Math.max(1,Number(current.version||0)+1);normalized.updatedAt=h.now();normalized.meta={...normalized.meta,seededAt:h.now(),source:"static-assets",hash:""};normalized.meta.hash=await hashState(h,normalized);return{state:normalized,info}}
async function hashState(h,state){const s=h.normalizeState(state);s.meta.hash="";return h.hashJson(s)}
function mask(h,state){const s=structuredClone(state);if(s.documents.schaeferCt.text)s.documents.schaeferCt.text=`[${h.byteLength(s.documents.schaeferCt.text)} Bytes]`;if(s.documents.schaeferMrt.text)s.documents.schaeferMrt.text=`[${h.byteLength(s.documents.schaeferMrt.text)} Bytes]`;return s}
function norm(x){return String(x||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
