export async function onRequestGet(context){const h=context.data.radprompt;h.method(["GET","HEAD"]);if(h.url.searchParams.get("empty")==="1"){const s=h.emptyState();s.meta.hash=await stateHash(h,s);return respond(h,s,{source:"empty",exists:false,written:false})}h.requireKv();const current=await readCurrent(h);if(!current.exists){const s=h.emptyState();s.meta.hash=await stateHash(h,s);return respond(h,s,{source:"empty",exists:false,written:false})}if(!current.readable)return h.json({ok:false,error:"invalid_state",message:"Gespeicherter State ist kein gültiges JSON.",runtime:h.runtime()},{status:409});return respond(h,current.state,{source:"kv",exists:true,written:false})}
export async function onRequestHead(context){const r=await onRequestGet(context);return new Response(null,{status:r.status,headers:r.headers})}
export async function onRequestPut(context){return replace(context)}
export async function onRequestPost(context){return replace(context)}
export async function onRequestPatch(context){const h=context.data.radprompt;h.method(["PATCH"]);h.requireKv();const body=await h.readJson();const current=await readCurrent(h);const base=current.exists&&current.readable?current.state:h.emptyState();const next=merge(h,base,body.patch||body);return write(h,next,current,body,"patch")}
export async function onRequestDelete(context){const h=context.data.radprompt;h.method(["DELETE"]);h.requireKv();if(h.url.searchParams.get("confirm")!=="delete")return h.json({ok:false,message:"Zum Löschen ?confirm=delete setzen.",runtime:h.runtime()},{status:400});const current=await readCurrent(h);let backup={ok:false,key:"",reason:"missing"};if(current.exists&&current.readable)backup=await h.backupState(current.state,"delete");await h.deleteKv(h.stateKey);return h.json({ok:true,deleted:current.exists,backup,runtime:h.runtime()})}
async function replace(context){const h=context.data.radprompt;h.method(["PUT","POST"]);h.requireKv();const body=await h.readJson();const incoming=body.state||body;if(!incoming||typeof incoming!=="object")return h.json({ok:false,message:"State fehlt.",runtime:h.runtime()},{status:400});const current=await readCurrent(h);const expected=cleanHash(body.expectedHash||h.request.headers.get("X-RadPrompt-Hash")||"");if(expected&&current.hash&&expected!==cleanHash(current.hash))return h.json({ok:false,error:"hash_conflict",currentHash:current.hash,runtime:h.runtime()},{status:409,headers:current.hash?{"X-RadPrompt-Hash":current.hash,ETag:etag(current.hash)}:{}});return write(h,incoming,current,body,"replace")}
async function readCurrent(h){const out={exists:false,readable:false,state:h.emptyState(),raw:"",hash:""};const raw=await h.getKv(h.stateKey);if(!raw){out.readable=true;out.hash=await stateHash(h,out.state);out.state.meta.hash=out.hash;return out}out.exists=true;out.raw=raw;try{out.state=h.normalizeState(JSON.parse(raw));out.readable=true;out.hash=out.state.meta.hash||await stateHash(h,out.state);out.state.meta.hash=out.hash}catch{out.hash=await h.hashText(raw)}return out}
async function write(h,incoming,current,body,mode){const s=h.normalizeState(incoming);s.version=Math.max(Number(current.state?.version||0)+1,Number(s.version||0),1);s.updatedAt=h.now();s.meta.hash="";s.meta.hash=await stateHash(h,s);const currentTag=current.hash?etag(current.hash):"";const ifMatch=h.request.headers.get("If-Match");if(ifMatch&&ifMatch!=="*"&&currentTag&&ifMatch!==currentTag)return h.json({ok:false,error:"precondition_failed",currentHash:current.hash,runtime:h.runtime()},{status:412});let backup={ok:false,key:"",reason:"missing"};if(current.exists&&current.readable&&body.backup!==false)backup=await h.backupState(current.state,`before-${mode}`);const payload=JSON.stringify(s);await h.putKv(h.stateKey,payload,{metadata:{schema:h.schema,version:s.version,updatedAt:s.updatedAt,hash:s.meta.hash,bytes:h.byteLength(payload),mode}});return respond(h,s,{source:"kv",exists:true,written:true,mode,backup})}
function merge(h,base,patch){const next=structuredClone(base);if(Array.isArray(patch.folders))next.folders=mergeById(next.folders,patch.folders.map(x=>h.normalizeFolder(x)));if(Array.isArray(patch.prompts))next.prompts=mergeById(next.prompts,patch.prompts.map(x=>h.normalizePrompt(x,next.folders[0]?.id||"allgemein")));if(Array.isArray(patch.favorites))next.favorites=h.unique([...next.favorites,...patch.favorites]);if(patch.documents)next.documents={...next.documents,...patch.documents};if(patch.settings)next.settings={...next.settings,...patch.settings};return h.normalizeState(next)}
function mergeById(a,b){const m=new Map((a||[]).map(x=>[x.id,x]));for(const x of b||[])m.set(x.id,{...(m.get(x.id)||{}),...x});return[...m.values()]}
async function respond(h,state,meta){const s=h.normalizeState(state);s.meta.hash=await stateHash(h,s);const body=h.url.searchParams.get("raw")==="1"?s:{ok:true,...meta,state:mask(h,s),summary:{...h.summarize(s),hash:s.meta.hash},runtime:h.runtime()};return h.json(body,{headers:{ETag:etag(s.meta.hash),"X-RadPrompt-Hash":s.meta.hash,"X-RadPrompt-Version":String(s.version)}})}
function mask(h,state){if(h.url.searchParams.get("text")!=="0"&&h.url.searchParams.get("documents")!=="0")return state;const s=structuredClone(state);if(s.documents?.schaeferCt?.text)s.documents.schaeferCt.text=`[${h.byteLength(s.documents.schaeferCt.text)} Bytes]`;if(s.documents?.schaeferMrt?.text)s.documents.schaeferMrt.text=`[${h.byteLength(s.documents.schaeferMrt.text)} Bytes]`;return s}
async function stateHash(h,state){const s=h.normalizeState(state);s.meta.hash="";return h.hashJson(s)}
function etag(hash){return`"radprompt-${cleanHash(hash)}"`}
function cleanHash(x){return String(x||"").replace(/^W\//,"").replace(/^"|"$/g,"").replace(/^radprompt-/,"")}
